Promise

  承诺机制

对象里放置的是异步处理函数，容器

如果异步函数执行成功，调用resolve函数

如果异步函数执行失败，调用reject函数

```js
let p = new Promise(function(resolve,reject){
    //异步操作
    $.ajax({
        url: '',
        type: '',
        success(res){
            resolve(res)
        },
        error(err){
            reject(err)
        }
    })
})
p.then(function(res){
    //内部异步成功处理函数
})     //resolve()
p.catch(function(err){
    //内部异步失败处理函数
})    //reject()
```

### 1.Promise的含义

Promise是异步编程的一种解决方案，比传统解决方案--回调函数和事件--更合理更强大。它由社区最早提出和实现，ES6将他写进了语言标准，统一了用法，原生提供了`Promise`对象。

所谓`Promise`,简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise是一个对象，从他那里可以获取异步操作的消息。Promise提供统一的API，各种异步操作都可以用同样的方法进行处理

`Promise`对象有以下两个特点

（1）对象的状态不受外界影响。`Promise`对象代表一个异步操作，有三种状态：`pending`(进行中)，`fulfilled`(已成功)和`reject`(已失败)。只有异步操作的结果，可以决定当前是哪一种状态，任何其它操作都无法改变这个状态。这也是`Promise`（承诺）这个名字的由来。

（2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。`Promise`对象的状态改变，只有两种可能：从`pending`变为`fulfilled`和从`pending`变为`rejected`。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为resolve（已定型）。如果改变已经发生了，你再对`Promise`对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是：如果你错过了，再去监听，是得不到结果的。

有了`Promise`对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，`Promise`对象提供统一的接口，使得控制异步操作更加容易。

`Promise`也有一些缺点。首先，无法取消`Promise`,一旦新建他就会立即执行，无法中途取消。其次如果不设置回调函数，`Promise`内部抛出的错误，不会反映到外部，第三，当处于`pending`状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）

### 2.基本用法

ES6规定，`Promise`对象是一个构造函数，用来生成`Promise`实例

下面代码创造了一个`Promise`实例

```js
const promise = new Promise(function(resolve,reject){
    //...
    if(/*异步操作成功*/){
       resolve(value)
    }else{
        //异步操作失败
        reject(error)
    }
})
```

`Promise`构造函数接受一个函数作为参数，该函数的两个参数分别是`resolve`和`reject`.他们是两个函数，由JavaScript引擎提供，不用自己部署。

`resolve`函数的作用是，将`Promise`对象的状态从“未完成”变成“成功”（即从pending变为resolve），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；`reject`函数的作用是，将`Promise`对象的状态从“未完成”变成“失败”（即从pending变为rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。

`Promise`实例生成以后，可以用`then`方法分别指定`resolved`状态和`rejected`状态的回调函数。

```js
promise.then(function(res){
    //success
},function(error){
    //error
})
```

`then`方法可以接受两个回调函数作为参数，第一个回调函数是`Promise`对象的状态变为`resolved`时调用，第二个回调函数是`Promise`对象的状态变为`rejected`时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接收`Promise`对象传出的值作为参数。

`Promise`简单例子

```js
function timeout(ms) {
    return new Promise((resolve,reject) => {
        setTimeout(resolve,ms,'done')
    })
}
timeout(100).then(value=>{
    console.log(value)
})
```

Promise新建后就会立即执行

```js
let promise = new Promise(function(resolve,reject){
    console.log('promise')
    resolve()
})
promise.then(function(){
    console.log('resolved')
})
console.log('hi')

//promise
//hi
//resolve
```

上面代码中，Promise新建后悔立即执行，所以首先输出的是'promise'.然后输出‘hi’，then方法指定的回调函数将在当前脚本所有同步任务执行完才会执行，所以resolved最后输出。

#### 嵌套使用

如果调用`resolve`函数和`reject`函数时带有参数，那么它们的参数会被传递给回调函数。`reject`函数的参数通常是`Error`对象的实例，表示抛出的错误；`resolve`函数的参数除了正常值以外，还可能是另一个Promise实例，比如像下面这样：

```js
const p1 = new Promise(function(resolve,reject){
    //...
})
const p2 = new Promise(function(resolve,reject){
    //...
    resolve(p1)
})
```

上面代码中p1和p2都是Promise的实例，但是p2的`resolve`方法将`p1`作为参数，即一个异步操作的结果是返回另一个异步操作。

注意：这时`p1`的状态就会传递给`p2`，也就是说，`p1`的状态决定了`p2`的状态。如果`p1`的状态是`pending`,那么`p2`的回调函数就会等待`p1`的状态改变；如果`p1`的状态已经是`resolved`或`rejected`,那么`p2`的回调函数将会立即执行。

### 3.Promise.prototype.then()

Promise实例具有`then`方法，也就是说，`then`方法是定义在原型对象`Promise.prototype`上的.它的作用是为Promise实例添加状态改变时的回调函数。`then`方法的第一个参数是`resolved`状态的回调函数，第二个参数（可选）是`rejected`状态的回调函数。

`then`方法返回的是一个新的`Promise`对象（注意：不是原来的那个`Promise`实例）。因此可以采用链式调用，即一个`then`方法后面再调用另一个`then`方法。

```js
getJSON('/posts.json').then(function(json){
    return json.post
}).then(function(post){
    //...
})
```

上面的代码使用`then`方法，依次指定了两个回调函数。第一个回调函数执行完后，会将返回结果作为参数，传入第二个回调函数。

采用链式的`then`,可以指定一组按照次序调用的回调函数，这时，前一个回调函数，有可能返回的还是一个`Promise`对象（即有异步操作），这时后一个回调函数，就会等待该`Promise`对象的状态发生改变，才会被调用。

### 4.Promise.prototype.catch()

`Promise.prototype.catch()`方法是`.then(null,rejection)`或`.then(undefined,rejection)`的别名，用于指定发生错误时的回调函数。`catch`方法返回的还是promise对象，因此后面还可以接着调用`then`方法

```js
getJSON('/posts.json').then(function(posts){
    //...
}).catch(function(error){
    console.log(error)
})
```

上面代码中，`getJSON`方法返回一个Promise对象，如果该对象状态变为`resolved`,则会调用`then`方法指定的回调函数；如果异步操作抛出错误，状态就会变为`rejected`,就会调用`catch`方法指定的回调函数，处理这个错误。另外，`then`方法指定的回调函数，如果运行中抛出错误，也会被`catch`方法捕获。

```js
p.then(val => console.log(val))
	.catch(err => console.log(err))

//等同于
p.then(val => console.log(val))
	.then(null,err => console.log(err))
```

例子：

```js
const promise = new Promise(function(resolve,reject){
    throw new Error('test')
})
promise.catch(function(error){
    console.log(error)
})
//Error: test
```

上面代码中，`promise`跑出一个错误，就被`catch`方法指定的回调函数捕获，下面两种写法与上面等价

```js
//写法一
const promise = new Promise(function(resolve,reject){
    try{
        throw new Error('test')
    } catch(e){
        reject(e)
    }
})
promise.catch(function(error){
    console.log(error)
})
//写法二
const promise = new Promise(function(resolve,reject){
    reject(new Error('test'))
})
promise.catch(function(error){
    console.log(error)
})
```

比较上面两种写法，可以发现`reject`方法的作用，等同于抛出错误

**注意：**如果Promise状态已经变成resolved，再抛出错误是无效的。

```js
const promise = new Promise(function(resolve,reject){
    resolve('ok')
    throw new Error('test')
})

promise.then(function(res){
    console.log(res)
}).catch(error){
    cosole.log(error)
}
// ok
```

上面的代码，Promise在`resolve`语句后面，再抛出错误，不会被捕获，等于没有抛出。因为Promise的状态一旦改变，就永久保持该状态，不会再改变了。

Promise对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止，也就是说，错误总是会被下一个`catch`语句捕获。一般来说，不要在`then`方法里面定义Reject扎UN柜台的回调函数（即`then`的第二个参数），总是使用`catch`方法

```js
//推荐写法
promise
	.then(function(data){
    //...
	})
	.catch(function(error){
    //...
	})
```

跟传统的`try/catch`代码块不同的是，如果没有使用`catch`方法指定错误处理的回调函数，Promise对象抛出的错误不会传递到外层代码，即不会有任何反应

### 5.Promise.prototype.finally()

`finally`方法用于指定不管Promise对象最后状态如何，都会执行的操作。该方法是ES2018引入标准的。

```js
promise
	.then(res => {...})
    .catch(err => {...})
     .finally(() => {...})
```

上面代码中不管`promise`最后状态如何，在执行完`then`或`catch`指定的回调函数后，都会执行`finally`方法指定的回调函数

`finally`方法的回调函数不接受任何参数，这意味着没有办法知道，前面的Promise状态到底是`fulfilled`还是`rejected`。这表明，`finally`方法里面的操作，应该是与状态无关的，不依赖于Promise的执行结果。

### 6.Promose.all()

`Promise.all`方法用于将多个Promise实例，包装成一个新的Promise实例

```js
const p = Promise.all([p1,p2,p3])
```

上面代码中，`Promise.all`方法接受一个数组作为参数，`p1`,`p2`,`p3`都是Promise实例，如果不是，就会先调用下面讲到的`promise.resolve`方法，将参数转为Promise实例，再进一步处理。（Promise.all方法的参数可以不是数组，但必须具有Iterator接口，且返回的每个成员都是Promises实例）

`p`的状态由`p1`,`p2`,`p3`决定，分成两种情况

（1）只有p1,p2,p3的状态都变成`fulfilled`,p的状态才会变成`fulfilled`,此时p1,p2,p3的返回值组成一个数组，传递给p的回调函数。

（2）只要p1,p2,p3之中有一个被`rejected`,p的状态就变成`rejected`,此时第一个被`rejected`的实例的返回值，会传递给p的回调函数。

### 7.Promise.race()

`Promise.race`方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。

```javascript
const p = Promise.race([p1, p2, p3]);
```

上面代码中，只要`p1`、`p2`、`p3`之中有一个实例率先改变状态，`p`的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给`p`的回调函数。

`Promise.race`方法的参数与`Promise.all`方法一样，如果不是 Promise 实例，就会先调用下面讲到的`Promise.resolve`方法，将参数转为 Promise 实例，再进一步处理。

下面是一个例子，如果指定时间内没有获得结果，就将 Promise 的状态变为`reject`，否则变为`resolve`。

```javascript
const p = Promise.race([
  fetch('/resource-that-may-take-a-while'),
  new Promise(function (resolve, reject) {
    setTimeout(() => reject(new Error('request timeout')), 5000)
  })
]);

p
.then(console.log)
.catch(console.error);
```

上面代码中，如果 5 秒之内`fetch`方法无法返回结果，变量`p`的状态就会变为`rejected`，从而触发`catch`方法指定的回调函数。

### 8.Promise.resolve()

有时需要将现有对象转为 Promise 对象，`Promise.resolve`方法就起到这个作用。

```javascript
const jsPromise = Promise.resolve($.ajax('/whatever.json'));
```

上面代码将 jQuery 生成的`deferred`对象，转为一个新的 Promise 对象。

`Promise.resolve`等价于下面的写法。

```javascript
Promise.resolve('foo')
// 等价于
new Promise(resolve => resolve('foo'))
```

`Promise.resolve`方法的参数分成四种情况。

**（1）参数是一个 Promise 实例**

如果参数是 Promise 实例，那么`Promise.resolve`将不做任何修改、原封不动地返回这个实例。

**（2）参数是一个thenable对象**

`thenable`对象指的是具有`then`方法的对象，比如下面这个对象。

```javascript
let thenable = {
  then: function(resolve, reject) {
    resolve(42);
  }
};
```

`Promise.resolve`方法会将这个对象转为 Promise 对象，然后就立即执行`thenable`对象的`then`方法。

```javascript
let thenable = {
  then: function(resolve, reject) {
    resolve(42);
  }
};

let p1 = Promise.resolve(thenable);
p1.then(function(value) {
  console.log(value);  // 42
});
```

上面代码中，`thenable`对象的`then`方法执行后，对象`p1`的状态就变为`resolved`，从而立即执行最后那个`then`方法指定的回调函数，输出 42。

**（3）参数不是具有then方法的对象，或根本就不是对象**

如果参数是一个原始值，或者是一个不具有`then`方法的对象，则`Promise.resolve`方法返回一个新的 Promise 对象，状态为`resolved`。

```javascript
const p = Promise.resolve('Hello');

p.then(function (s){
  console.log(s)
});
// Hello
```

上面代码生成一个新的 Promise 对象的实例`p`。由于字符串`Hello`不属于异步操作（判断方法是字符串对象不具有 then 方法），返回 Promise 实例的状态从一生成就是`resolved`，所以回调函数会立即执行。`Promise.resolve`方法的参数，会同时传给回调函数。

**（4）不带有任何参数**

`Promise.resolve()`方法允许调用时不带参数，直接返回一个`resolved`状态的 Promise 对象。

所以，如果希望得到一个 Promise 对象，比较方便的方法就是直接调用`Promise.resolve()`方法。

```javascript
const p = Promise.resolve();

p.then(function () {
  // ...
});
```

上面代码的变量`p`就是一个 Promise 对象。

需要注意的是，立即`resolve()`的 Promise 对象，是在本轮“事件循环”（event loop）的结束时执行，而不是在下一轮“事件循环”的开始时。

```javascript
setTimeout(function () {
  console.log('three');
}, 0);

Promise.resolve().then(function () {
  console.log('two');
});

console.log('one');

// one
// two
// three
```

上面代码中，`setTimeout(fn, 0)`在下一轮“事件循环”开始时执行，`Promise.resolve()`在本轮“事件循环”结束时执行，`console.log('one')`则是立即执行，因此最先输出。

### 9.Promise.reject()

`Promise.reject(reason)`方法也会返回一个新的 Promise 实例，该实例的状态为`rejected`。

```javascript
const p = Promise.reject('出错了');
// 等同于
const p = new Promise((resolve, reject) => reject('出错了'))

p.then(null, function (s) {
  console.log(s)
});
// 出错了
```

上面代码生成一个 Promise 对象的实例`p`，状态为`rejected`，回调函数会立即执行。

注意，`Promise.reject()`方法的参数，会原封不动地作为`reject`的理由，变成后续方法的参数。这一点与`Promise.resolve`方法不一致。

```javascript
const thenable = {
  then(resolve, reject) {
    reject('出错了');
  }
};

Promise.reject(thenable)
.catch(e => {
  console.log(e === thenable)
})
// true
```

上面代码中，`Promise.reject`方法的参数是一个`thenable`对象，执行以后，后面`catch`方法的参数不是`reject`抛出的“出错了”这个字符串，而是`thenable`对象。







